### ISSUE TITLE
make the macroskeleton txts for PUEO

### ISSUE THREAD

**Issue by dylanwells37** [osu-particle-astrophysics/GENETIS_PUEO#20]

**Comment by Machtay** [comment]
I made modifications to the original macroskeleton files we had from the ARA version of the loop. The primary differences are in the geometry being made and in the number of simulations we make. Instead of one simulation per antenna, we need to simulate each of these antennas twice because there are two power sources. Each ridge is connected to the ridge opposite it by a power source, representing the vpol and hpol channels of the antenna.
